const alphabet = ["a", "á",
    "b",
    "c", "cs",
    "d", "dz", "dzs",
    "e", "é",
    "f",
    "g", "gy",
    "h",
    "i", "í",
    "j",
    "k",
    "l", "ly",
    "m",
    "n", "ny",
    "o", "ó", "ö", "ő",
    "p",
    "q",
    "r",
    "s", "sz",
    "t", "ty",
    "u", "ú", "ü", "ű",
    "v",
    "w",
    "x",
    "y",
    "z", "zs"
];

const words = [
    { letter: 'a', word: 'autó', index: 0 },
    { letter: 'á', word: 'sárkány', index: 1 },
    { letter: 'b', word: 'baba', index: 0 },
    { letter: 'c', word: 'maci', index: 2 },
    { letter: 'cs', word: 'csörgő', index: 0 },
    { letter: 'd', word: 'dínó', index: 0 },
    { letter: 'dz', word: 'dz', index: 0 },
    { letter: 'dzs', word: 'dzs', index: 0 },
    { letter: 'e', word: 'gördeszka', index: 4 },
    { letter: 'é', word: 'építőkocka', index: 0 },
    { letter: 'f', word: 'fényképező', index: 0 },
    { letter: 'g', word: 'gördeszka', index: 0 },
    { letter: 'gy', word: 'gyík', index: 0 },
    { letter: 'h', word: 'helikopter', index: 0 },
    { letter: 'i', word: 'nyuszi', index: 5 },
    { letter: 'í', word: 'síp', index: 1 },
    { letter: 'j', word: 'jojó', index: 0 },
    { letter: 'k', word: 'katona', index: 0 },
    { letter: 'l', word: 'labda', index: 0 },
    { letter: 'ly', word: 'üveggolyó', index: 2 },
    { letter: 'm', word: 'maci', index: 0 },
    { letter: 'n', word: 'fonal', index: 2 },
    { letter: 'ny', word: 'nyuszi', index: 0 },
    { letter: 'o', word: 'katona', index: 3 },
    { letter: 'ó', word: 'szélforgó', index: 8 },
    { letter: 'ö', word: 'gördeszka', index: 1 },
    { letter: 'ő', word: 'repülő', index: 5 },
    { letter: 'p', word: 'fényképező', index: 6 },
    { letter: 'q', word: 'q', index: 0 },
    { letter: 'r', word: 'robot', index: 0 },
    { letter: 's', word: 'sárkány', index: 0 },
    { letter: 'sz', word: 'számítógép', index: 0 },
    { letter: 't', word: 'táska', index: 0 },
    { letter: 'ty', word: 'tyúk', index: 0 },
    { letter: 'u', word: 'ugrókötél', index: 0 },
    { letter: 'ú', word: 'tyúk', index: 2 },
    { letter: 'ü', word: 'üveggolyó', index: 0 },
    { letter: 'ű', word: 'űrhajó', index: 0 },
    { letter: 'v', word: 'vonat', index: 0 },
    { letter: 'w', word: 'w', index: 0 },
    { letter: 'x', word: 'xilofon', index: 0 },
    { letter: 'y', word: 'y', index: 0 },
    { letter: 'z', word: 'zebra', index: 0 },
    { letter: 'zs', word: 'zsiráf', index: 0 }
];
